version: '3'

services:
  app_database:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: app_user
      POSTGRES_DB: app_db
      POSTGRES_PASSWORD: app_password
    ports:
      - "5432:5432"

  app:
    image: app
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - app_database
    environment:
      DATABASE_URL: postgresql://app_user:app_password@app_database:5432/app_db
    volumes:
      - ./app:/app/app

volumes:
  pgdata: