"""creating field group in table competitor

Revision ID: a88a58e25650
Revises: 5bb07b0d4f67
Create Date: 2024-01-31 08:22:37.988203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a88a58e25650'
down_revision: Union[str, None] = '5bb07b0d4f67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE competitor_group AS ENUM ('group_1', 'group_2')")
    op.add_column('competitors', sa.Column('group', sa.Enum('group_1', 'group_2', name='competitor_group'), nullable=True))
    op.create_unique_constraint(None, 'competitors', ['id'])
    op.create_unique_constraint(None, 'tournaments', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tournaments', type_='unique')
    op.drop_constraint(None, 'competitors', type_='unique')
    op.drop_column('competitors', 'group')
    # ### end Alembic commands ###
