"""criando o campo is_strat

Revision ID: cf91bca50aa6
Revises: af9cd3605943
Create Date: 2024-02-04 16:40:56.277275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf91bca50aa6'
down_revision: Union[str, None] = 'af9cd3605943'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournaments', 'is_active')
    # ### end Alembic commands ###
